name: lsif-build

on:
  push:
    branches:
      - lsif
  pull_request:
    branches:
      - lsif

jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: cd ./packages/pyright-lsif/ && npm install && npm run build
